# This workflow builds your CMake project on Ubuntu, installs
# system FreeGLUT/OpenGL dev packages, and creates the symlinks
# needed to satisfy Windows‐style includes and library names.
name: CMake build (Ubuntu)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize this to Debug, RelWithDebInfo, etc.
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenGL & FreeGLUT development packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            freeglut3-dev \
            libglu1-mesa-dev \
            mesa-common-dev

      - name: Create symlink for GLUT headers
        # your code does #include <gl/glut.h>, but Ubuntu uses /usr/include/GL
        run: sudo ln -sf /usr/include/GL /usr/include/gl

      - name: Create symlinks for OpenGL libraries
        # your CMake still links to opengl32 and glu32
        run: |
          sudo ln -sf /usr/lib/x86_64-linux-gnu/libGL.so  /usr/lib/x86_64-linux-gnu/libopengl32.so
          sudo ln -sf /usr/lib/x86_64-linux-gnu/libGLU.so /usr/lib/x86_64-linux-gnu/libglu32.so

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ env.BUILD_TYPE }}
